### ISSUE TITLE
Éléments qui se chevauchent, affichage bugué 

### ISSUE THREAD

**Issue by treyssatvincent** [PartiPirate/tools#19]
Sous Firefox (à jour) : 
![screenshot from 2017-07-07 15-23-16](https://user-images.githubusercontent.com/18269685/27959685-bbab34ae-6328-11e7-9bb4-dbe7376b5725.png)

Sous Brave (equivalent à Chromium, à jour) : 
![screenshot from 2017-07-07 15-24-02](https://user-images.githubusercontent.com/18269685/27959691-bf05d97e-6328-11e7-8d5b-62715fdd852e.png)

**Comment by janroudaut** [comment]
Tout à fait d'accord avec @treyssatvincent, c'est même pour ça que j'ai accouru sur le repository pour voir ce qu'il en était...

Si le dépôt est toujours actif (@farlistener ?) et que ça a des chances d'être déployé, je veux bien m'occuper de tweaker un peu les feuilles de style pour arranger le layout et soumettre un PR.
