### ISSUE TITLE
Erreur javascipt pour rajouter une compétence

### ISSUE THREAD

**Issue by anayrat** [PartiPirate/tools#22]
Bonjour,

J'ai une erreur javascript pour rajouter une compétence depuis la page https://tools.partipirate.org/

Si je clique sur le bouton "Ajouter", il ne se passe rien et dans la console javascript j'ai cette erreur : 
```
index.js:82 Uncaught TypeError: dialog.modal is not a function
    at HTMLButtonElement.showAddSkillModalHandler (index.js:82)
    at HTMLDivElement.dispatch (jquery-1.11.1.min.js:3)
    at HTMLDivElement.r.handle (jquery-1.11.1.min.js:3)
showAddSkillModalHandler @ index.js:82
dispatch @ jquery-1.11.1.min.js:3
r.handle @ jquery-1.11.1.min.js:3
```

J'ai testé avec opera, chrome et firefox sans succès.

Merci

**Comment by melimea** [comment]
Le problème semble maintenant résolu chez moi.

**Comment by anayrat** [comment]
Je confirme, ça semble résolu. Du coup ferme l'issue ;)
