### ISSUE TITLE
[Approbation] : choix negatif inexistant

### ISSUE THREAD

**Issue by kilyx** [PartiPirate/tools#9]
Est il possible de positionner un vote negatif sur l'approbation de la fenetre de droite lorsque une personne dit qu'elle maitrise un sujet alors que l'on penses que non ou inversement ?

**Comment by farlistener** [comment]
Ça serait possible, mais à la base nous ne voulions pas de mise au pilori par ce biais

**Comment by kilyx** [comment]
ok alors je cloture la demande.
